<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFrameworks>net472;net9.0</TargetFrameworks>
        <LangVersion>10</LangVersion>
        <ApplicationIcon>ReportWithChart.ico</ApplicationIcon>
        <Version>2026.5.0</Version>
        <Authors>Eric R. Zimmerman</Authors>
        <Description>Dumps SRUM data to CSV</Description>
        <Copyright>Eric R. Zimmerman</Copyright>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AlphaFS.New" Version="2.3.0" />
        <PackageReference Include="Costura.Fody" Version="6.0.0">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CsvHelper" Version="33.1.0" />
        <PackageReference Include="Exceptionless" Version="6.1.0" />
        <PackageReference Include="Fody" Version="6.9.3">
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Serilog" Version="4.3.1" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />

        <PackageReference Include="ServiceStack.Text" Version="10.0.6" />
        
	<PackageReference Include="System.CommandLine" Version="2.0.7" />
        <PackageReference Include="System.CommandLine.NamingConventionBinder" Version="2.0.0-beta4.22272.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\SrumData\SrumData.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Properties" />
    </ItemGroup>

</Project>
